module.exports = {
  //LEVEL
  CET_4: 'CET_4',
  CET_6: 'CET_6',
  //SECTION TITLE
  NEWS_REPORT: 'NEWS_REPORT',
  CONVERSATION: 'CONVERSATION',
  PASSANGE: 'PASSANGE',
  RECORD: 'RECORD',
  //VIEW PAPER mode
  PRACTICE: 'PRACTICE',
  TEST: 'TEST'
  //AUDIO PLAYER STATUS
  // NO_AUDIO_URL: 'NO_AUDIO_URL',
  // LOADING_AUDIO_URL: 'LOADING_AUDIO_URL'
}